agent:
  host: 192.168.108.127
  port: 8090
database:
  dbname: posdb
  hostname: localhost
  password: 123456
  username: postgres
proxies:
- alias: STM Contagem 15
  auto_connect: true
  name: STM Contagem 15
  origin: 192.168.108.127:2001
  port: 6815
  reconnect_inverval: 10
- alias: FSMAE015
  auto_connect: true
  name: FSMAE015
  origin: 192.168.108.127:2002
  port: 6802
  reconnect_inverval: 2
- alias: STM Contagem 05
  auto_connect: true
  name: STM Contagem 05
  origin: 192.168.108.127:2003
  port: 6805
  reconnect_inverval: 10
- alias: STM Contagem 07
  auto_connect: true
  name: STM Contagem 07
  origin: 192.168.108.127:2004
  port: 6807
  reconnect_inverval: 10
- alias: STM Contagem 14
  auto_connect: true
  name: STM Contagem 14
  origin: 192.168.108.127:2004
  port: 6814
  reconnect_inverval: 10
- alias: STM Contagem 17
  auto_connect: true
  name: STM Contagem 17
  origin: 192.168.108.127:2005
  port: 6817
  reconnect_inverval: 10
- alias: STM Contagem 19
  auto_connect: true
  name: STM Contagem 19
  origin: 192.168.108.127:2006
  port: 6819
  reconnect_inverval: 10
- alias: STM Contagem 20
  auto_connect: true
  name: STM Contagem 20
  origin: 192.168.108.127:2007
  port: 6820
  reconnect_inverval: 10
- alias: STM Contagem 24
  auto_connect: true
  name: STM Contagem 24
  origin: 192.168.108.127:2008
  port: 6824
  reconnect_inverval: 10
- alias: STM Contagem 26
  auto_connect: true
  name: STM Contagem 26
  origin: 192.168.108.127:2009
  port: 6826
  reconnect_inverval: 10
- alias: STM Contagem 28
  auto_connect: true
  name: STM Contagem 28
  origin: 192.168.108.127:2010
  port: 6827
  reconnect_inverval: 10
- alias: STM Contagem 30
  auto_connect: true
  name: STM Contagem 30
  origin: 192.168.108.127:2011
  port: 6828
  reconnect_inverval: 10
- alias: STM Contagem 32
  auto_connect: true
  name: STM Contagem 32
  origin: 192.168.108.127:2012
  port: 6830
  reconnect_inverval: 10
- alias: STM Contagem 36
  auto_connect: true
  name: STM Contagem 36
  origin: 192.168.108.127:2013
  port: 6832
  reconnect_inverval: 10
- alias: STM Contagem 40
  auto_connect: true
  name: STM Contagem 40
  origin: 192.168.108.127:2014
  port: 6836
  reconnect_inverval: 10
- alias: STM Contagem 44
  auto_connect: true
  name: STM Contagem 44
  origin: 192.168.108.127:2015
  port: 6838
  reconnect_inverval: 10
- alias: STM Contagem 48
  auto_connect: true
  name: STM Contagem 48
  origin: 192.168.108.127:2016
  port: 6840
  reconnect_inverval: 10
servers:
- name: Server 1
  port: 1001
  serial: '2000774'
smb:
  enabled: true
  interval_in_seconds: 5
  password: Admin@123
  reconnect_inverval: 10
  root: /
  server: BNS
  service: TestShared
  username: Administrator
